### ISSUE TITLE
Error loading package due to 'Cuis-Base' version number

### ISSUE THREAD

**Issue by billthehistorian** [Cuis-Smalltalk/Morphic#1]
I encountered the following error running Feature require: 'allPackages'
```
 
Could not find package supplying: FeatureRequirement(Cuis-Base 50.4568 to *.*)
Required by: FeatureRequirement(Morphic-Misc1 1.0 to *.*)
For installing: FeatureRequirement(allPackages *.*))

You can view loaded Packages and their requirements via World menu > Open.. > Installed Packages
```
Changing  "!requires: 'Cuis-Base' 50 456**8** nil to the current image version (!requires: 'Cuis-Base' 50 456**7** nil) allowed all packages to load.

I submitted a PR, but not sure if this should be changed to 50.4567 or an older image.

**Comment by KenDickey** [comment]
When using a Cuis image, it is useful periodically to update (e.g. run the pullAllRepos.sh script or at least "git update") and then, in the Cuis Image, 
  World Menu -> Changes -> Install New Updates .
This currently brings the Base image to rev 4594.
As 4594 > 4568, the #'Morphic-Misc1' Feature requirement should be satisfied.

The requirement is not an error -- the Morphic-Misc1 package really wants a newer base version than 4568.  What better wording/action would help convey this?
-KenD

**Comment by billthehistorian** [comment]
Ken,

No need to make the instructions clearer, the error was overeagerness and
incompetence on my part. I am new to Cuis and Smalltalk in general; this
was my first attempt at contributing to anything. Next time I'll just ask
someone.

 I had just reinstalled the new Cuis image from scratch and had run
pullAllRepos (all good), but apparently the changes to the image after the
Install New Updates step were not saved (I was sure they did, I'm still not
sure why they didn't).

The double GitHub submission on the other hand was from some confusing
feedback, but from GitHub itself.

All around an inauspicious and embarrassing debut to the community—and Ken
Dickey of all people. Oof.

-Bill D

**Comment by KenDickey** [comment]
On 2021-05-19 17:52, billthehistorian wrote:

> .. I am new to Cuis and Smalltalk in general; this
> was my first attempt at contributing to anything.
..

No worries.  I always say that I _like_ "pilot error".  It is the 
easiest thing for me to fix!  ;^)

> All around an inauspicious and embarrassing debut to the community--and 
> Ken
> Dickey of all people.

Hey, if you had a dime for all the dumb things I did you could probably 
retire.

Your contributions to the community are as welcome as mine.

One foot in front of the other.

Good on ya,
-KenD
